version: 2.0
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run:
          name: Setup proxy
          command:
            curl -sL https://art.sec.samsung.net/artifactory/tools/CircleCI/scripts/set_proxy_setting.sh | sh
      - run:
          name: JuvoReactNative exclusion
          command: dotnet sln remove JuvoReactNative/Tizen/JuvoReactNative.csproj
      - run:
          name: Build 
          command: dotnet build -c Release JuvoPlayer.sln
      - run:
          name: Tests
          command: |
               dotnet test /nodeReuse:false JuvoPlayer.Tests/JuvoPlayer.Tests.csproj --logger "trx" -f netcoreapp2.1 --verbosity=normal
      - run: 
          name: test results
          command: |
              dotnet tool install -g trx2junit
              export PATH="$PATH:/root/.dotnet/tools"
              trx2junit tests/**/TestResults/*.trx
      - store_test_results:
          path: tests/TestResults
          destination: TestResults

