version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
            ssh -T git@github.sec.samsung.net
            
            
      - run:
          name: Build and Test JuvoPlayer
          command: /home/p.buczynski/git/code/juvo-player/bamboo-specs/build_and_test.sh            
