version: 2.0
jobs:
  build:
    docker:
      - image:  microsoft/aspnetcore-build:2.0
    steps:
      - checkout
      - run:
          name: Setup proxy
          command:
            curl -sL https://art.sec.samsung.net/artifactory/tools/CircleCI/scripts/set_proxy_setting.sh | sh
      - run:
          name: JuvoReactNative exclusion
          command: dotnet sln remove JuvoReactNative/Tizen/JuvoReactNative.csproj
      - run:
          name: Build 
          command: dotnet build -c Release JuvoPlayer.sln
      - run:
          name: Tests
          command: dotnet test /nodeReuse:false JuvoPlayer.Tests/JuvoPlayer.Tests.csproj --logger:trx -f netcoreapp2.0